services:
  - type: worker            # ← исправили
    name: pybotrefunds1
    runtime: python         # заменяет устаревшее env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python bot1.py
    envVars:
      - key: BOT_TOKEN
        sync: false         # задашь значение в Dashboard
