services:
  - type: background_worker        # для long-running polling-бота
    name: pybotrefunds1
    env: python
    plan: starter                  # free-тарифов для background_worker нет
    region: frankfurt              # ближе к России — меньше пинга
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python bot1.py               # или другой entry-point
    envVars:
      - key: BOT_TOKEN             # переменные задашь в Dashboard
        sync: false
