services:
  - type: web
    name: refunds-bot
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_webhook.py
    autoDeploy: true

    envVars:
      - key: BOT_TOKEN        # значение зададите в Dashboard
        sync: false

      - key: WEBHOOK_HOST     # https://refunds-bot.onrender.com
        sync: false           # value убрали, чтобы не было конфликта
